version: '3.8'

services:
  dashboard-app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    expose:
      - "3000"
    container_name: dashboard

  nginx:
    image: nginx:alpine
    container_name: nginx-alpine
    ports: 
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dashboard-app
